apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-persistent-volume
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /vl
    server: 172.28.0.7
