apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
